<h3 class="top">Счетчик электроэнергии</h3>
<div class="menu">
	<div>
		<a href="/index.htm">Главная</a>
		<a href="/history.htm">История по дням, часам</a>
		<a href="/historyall.htm">История детально</a>
		<a href="/lastkwt.htm">График</a>
	</div>
	<div>
		<a href="/protect/setmeter.htm">Настройка</a>
		<a href="/settings.htm">Дополнительно</a>
		<a href="/timelogs.htm">Логи</a>
		<a href="/bymonth.htm">Итого помесячно</a>
	</div>
</div>
<script type="text/javascript">
for (var i = 0; i < document.links.length; i++) {
    if (document.links[i].href == document.URL) {
        document.links[i].className = 'active';
    }
}
</script>